# Generated by Django 3.2.20 on 2023-07-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecard',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Disapproved')], default=0),
        ),
    ]
