# Generated by Django 3.2.20 on 2023-07-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musa', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vote_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_card',
            field=models.ManyToManyField(related_name='user_cards', through='vote_management.VoteRecord', to='vote_management.VoteCard'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
