# Generated by Django 3.2.20 on 2023-07-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electedperson',
            name='vote_card',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_candidate', to='musa.votecard'),
        ),
    ]
