# Generated by Django 3.2.20 on 2023-07-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musa', '0002_alter_userprofile_user_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_record', to='musa.voterecord'),
        ),
    ]
