# Generated by Django 3.2.20 on 2023-07-27 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musa', '0004_remove_userprofile_user_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterecord',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
