# Generated by Django 3.2.20 on 2023-07-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musa', '0005_alter_voterecord_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecard',
            name='expire',
            field=models.DateField(),
        ),
    ]
