# Generated by Django 3.2.20 on 2023-07-31 15:52

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='ElectedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_elected', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('mission', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=400)),
                ('expire', models.DateField()),
                ('event_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Disapproved')], default=0)),
                ('excerpt', models.TextField(blank=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_author', to=settings.AUTH_USER_MODEL)),
                ('candidates', models.ManyToManyField(blank=True, related_name='vote_cards', to='vote_management.ElectedPerson')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vote_management.category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('elected_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elected_record', to='vote_management.electedperson')),
                ('vote_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votecard_record', to='vote_management.votecard')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='votecard',
            name='vote_record',
            field=models.ManyToManyField(blank=True, related_name='user_votes', through='vote_management.VoteRecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electedperson',
            name='vote_card',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_candidate', to='vote_management.votecard'),
        ),
    ]
