# Generated by Django 3.2.20 on 2023-08-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecard',
            name='location',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='votecard',
            name='mission',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='votecard',
            name='title',
            field=models.CharField(max_length=33, unique=True),
        ),
    ]
