# Generated by Django 3.2.20 on 2023-08-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecard',
            name='type',
            field=models.IntegerField(choices=[(0, 'Community'), (1, 'Official')], default=0),
        ),
    ]
