# Generated by Django 3.2.20 on 2023-08-08 13:10

import cloudinary.models
from django.db import migrations
import vote_management.image_validation


class Migration(migrations.Migration):

    dependencies = [
        ('vote_management', '0002_auto_20230807_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecard',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, validators=[vote_management.image_validation.validate_image_size], verbose_name='image'),
        ),
    ]
