# Generated by Django 3.2.20 on 2023-08-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_management', '0002_alter_votecard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecard',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Online'), (2, 'Cancelled'), (3, 'Completed')], default=0),
        ),
    ]
