# Generated by Django 3.2.20 on 2023-08-08 13:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_management', '0003_alter_votecard_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecard',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
