# Generated by Django 3.2.20 on 2023-08-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_management', '0003_alter_votecard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecard',
            name='description',
            field=models.TextField(max_length=258),
        ),
        migrations.AlterField(
            model_name='votecard',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='votecard',
            name='mission',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='votecard',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
